#!/bin/bash

fileName="$1"

if [ "$#" -eq 0 ]
then 
	fileName=`date`
fi

[ ! -d "~/.recs" ] && mkdir ~/.recs
[ ! -d "~/.recs/calls" ] && mkdir ~/.recs/calls

amixer -c 0 -- sset "Capture",0 80 cap
amixer sset "Mic Boost" 2

ffmpeg \
-f pulse -ac 2 -ar 48000 -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor \
-f pulse -ac 2 -ar 48000 -i alsa_input.pci-0000_00_1f.3.analog-stereo \
-filter_complex amix=inputs=2 \
-f x11grab  -video_size 1920x1080 -framerate 30 -i :0.0+0,0 -c:v libx264 -crf 0 -preset ultrafast \
/home/andrii/.recs/calls/"$fileName".mkv

amixer sset "Mic Boost" 0
amixer -c 0 -- sset "Capture",0 0 cap
