#!/bin/bash

# pactl list short sources

theme="$1"
recDate=`date +%Y-%m-%d_%R_`

[ ! -d "~/backup/recs" ] && mkdir ~/backup/recs

# PC cable headphones with mic
# -f pulse -ac 2 -ar 48000 -i alsa_output.pci-0000_00_14.2.analog-stereo.monitor \
# -f pulse -ac 2 -ar 48000 -i alsa_input.pci-0000_00_14.2.analog-stereo \

filePath=~/backup/recs/"${recDate}${theme}"
fileFormat=mkv
outFile=$filePath.$fileFormat
fixedFile=$filePath--delayed.$fileFormat
inputDevice="alsa_input.usb-Microsoft_Microsoft_LifeCam_VX-5000-02.mono-fallback"
outputDevice="bluez_output.20_74_CF_ED_C3_4E.a2dp-sink"

# unmute mic
pactl set-source-mute $inputDevice 0
#set mic volume level
pactl set-source-volume $inputDevice 120%
# pactl set-sink-volume $outputDevice 50%

ffmpeg \
  -f pulse -ac 1 -ar 48000 -i $inputDevice \
  -f pulse -ac 2 -ar 48000 -i $outputDevice \
  -filter_complex amix=inputs=2 \
  -f x11grab -video_size 2560x1440 -framerate 30 -hwaccel cuda -hwaccel_output_format cuda \
  -i :0.0+0,0 -c:v h264_nvenc -b 300M $outFile

# there is an audio track delay when grab from bluetooth device
# this line use -itsoffset option to delay video to some seconds
ffmpeg -y -i $outFile -itsoffset 2.2 -i $outFile -map 1:v -map 0:a -c copy $fixedFile
# the original file is not needed anymore
rm $outFile
mv $fixedFile $outFile

# mute mic
pactl set-source-mute $inputDevice 1
