#!/bin/bash

# pactl list short sources

theme="$1"
recDate=`date +%Y-%m-%d_%R_`

[ ! -d "~/backup/recs" ] && mkdir ~/backup/recs

# PC cable
# -f pulse -ac 2 -ar 48000 -i alsa_output.pci-0000_00_14.2.analog-stereo.monitor \
# -f pulse -ac 2 -ar 48000 -i alsa_input.pci-0000_00_14.2.analog-stereo \

# PC aux+mic over wev cam (pipewire device names)
# -f pulse -ac 2 -ar 48000 -i bluez_sink.41_42_D6_00_4E_90.a2dp_sink.monitor \
# -f pulse -ac 2 -ar 48000 -i alsa_input.usb-Microsoft_Microsoft_LifeCam_VX-5000-02.mono-fallback \

# PC full aux (pipewire device names)
# -f pulse -ac 2 -ar 48000 -i bluez_output.41_42_D6_00_4E_90.headset-head-unit.monitor \
# -f pulse -ac 2 -ar 48000 -i bluez_input.41_42_D6_00_4E_90.headset-head-unit \

inputDevice="alsa_input.usb-Microsoft_Microsoft_LifeCam_VX-5000-02.pro-input-0"
outputDevice="bluez_output.20_74_CF_ED_C3_4E.a2dp-sink"

pactl set-source-mute $inputDevice 0
# pactl set-source-volume $inputDevice 78%

ffmpeg \
  -f pulse -i $inputDevice \
  -f pulse -i $outputDevice \
  -filter_complex amix=inputs=2 \
  -f x11grab  -video_size 2560x1440 -framerate 30 -hwaccel cuda -hwaccel_output_format cuda -i :0.0+0,0 -c:v h264_nvenc -b 500M -preset slow -rc vbr \
  ~/backup/recs/"${recDate}${theme}".mkv

pactl set-source-mute $inputDevice 1
