#!/bin/bash

fileName="$1"

if [ "$#" -eq 0 ]
then 
	fileName=`date`
fi

[ ! -d "~/.recs" ] && mkdir ~/.recs
[ ! -d "~/.recs/mic" ] && mkdir ~/.recs/mic

amixer -c 0 -- sset "Capture",0 80 cap
amixer sset "Mic Boost" 3
amixer sset "Internal Mic Boost" 2

ffmpeg -f pulse -ac 2 -ar 48000 -i alsa_input.pci-0000_00_1f.3.analog-stereo /home/andrii/.recs/mic/"$fileName".wav

amixer sset "Mic Boost" 0
amixer sset "Internal Mic Boost" 0
amixer -c 0 -- sset "Capture",0 0 cap
